name: sync-from-coding-devops
on:
  schedule:
    # 早晚10点各同步一次
    - cron: "0 10,22 * * *"
  # https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/git-sync-action
      - name: sync-to-coding-devops
        uses: wei/git-sync@v3
        with:
          source_repo: https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@e.coding.net/quanttide/qtopen-python/coding-devops-sdk-py.git
          source_branch: master
          destination_repo: quanttide/coding-devops-sdk-py
          destination_branch: master