name: sync-from-coding-devops
on:
  # webhook

jobs:
  steps:
    sync:
      steps:
        # https://github.com/marketplace/actions/github-repo-sync
        - use: repo-sync/github-sync@v2
          with:
            source_repo: ''
            source_branch: master
            destination_branch: master
            sync_tags: true